HW2
ok-technopolis-2020/Sachuk_Ilya pull request #2
Opened 2020-11-04 21:25 UTC by IlyaAAAA

2020-11-05 05:46 UTC, fromanywhere requested changes

2020-11-05 05:46 UTC, fromanywhere commented on styles.css
> +header h1 {
убираем каскад

2020-11-05 05:46 UTC, fromanywhere commented on styles.css
> +    width: 20px;
увеличиваем площадь кнопки 
![image](https://user-images.githubusercontent.com/1042969/98201845-acf4ed00-1f41-11eb-95ae-685a041390dc.png)

2020-11-05 05:46 UTC, fromanywhere commented on styles.css
> +}
а где обводочки у табов? и нужно, чтобы там на фокус всё подсвечивалось и не прыгало по горизонтали при переключении

2020-11-05 05:46 UTC, fromanywhere commented on styles.css
> +}
где-то тут утеряна двойная тень 
![image](https://user-images.githubusercontent.com/1042969/98202139-6784ef80-1f42-11eb-8c9b-a3d0c4c1e06e.png)

2020-11-05 05:46 UTC, fromanywhere commented on styles.css
> +/* не вижу есть ли разница*/
всё ок

2020-11-06 15:15 UTC, fromanywhere requested changes

2020-11-06 15:15 UTC, fromanywhere commented on styles.css
> +}
Тени всё еще утеряны

2020-11-06 16:17 UTC, step-ponomarev commented on styles.css
> +}
А что за двойная тень?

2020-11-06 16:19 UTC, IlyaAAAA commented on styles.css
> +}
подложка?

2020-11-10 14:27 UTC, fromanywhere approved these changes

2020-11-10 15:21 UTC, merged